### ISSUE TITLE
Web Push doesn't open app, if the app is in background

### ISSUE THREAD

**Issue by vlasovilya** [GoogleChromeLabs/svgomg-twa#20]
Web Push click does open the app if the app is fully closed, but if it is in background click does nothing. 

Service worker code:

`self.addEventListener('notificationclick', function(event){
        event.notification.close();
        event.waitUntil(clients.matchAll({
           type: "window"
        }).then(function(clientList) {

            var url=event.notification.data.url || '/';

            for (var i = 0; i < clientList.length; i++) {            
                if ('focus' in client){
                    return client.focus();
                }
            }
            if (clients.openWindow) {
                return clients.openWindow(url);
            }
        }));
    });`

Looks like `client.focus` and `clients.openWindow` doesn't work, if the app is in background

**Comment by LukasSarnowskiC9** [comment]
I have the same problem as vlasovilya and my service worker code looks the same as his. Everything is working fine when the app runs as PWA but not as TWA.

**Comment by andreban** [comment]
Can you provide more information on the browser version? Also, can you take a look on #15 and point if that is a similar issue?

**Comment by LukasSarnowskiC9** [comment]
I have tested this on Android Studio Emulator (Chrome 74 and 75 on android 7.0 and 8.0), on Pixel XL (Android 8.0, Chrome 74 and 75) and on Huawei (Android 8.0, Chrome 74). On the Pixel devices the clients.openWindow(url) is ignored when the app is in background (not waking up the app) and on Huawai the app just closes/crashes when in background/foreground (it only opens the app when it is completely closed). When i run the page as PWA the clients.openWindow(url) brings the app to the foreground as expected.

**Comment by andreban** [comment]
re: the issue with Pixel and Chrome 74 / 75, could you please test on Chrome Canary? An issue with bringing was fixed and is available there.

**Comment by LukasSarnowskiC9** [comment]
Thank you for the information andreban. I have now tested my TWA with the canary Chrome version and it is working as intended.

**Comment by kolyuchii** [comment]
Hello @vlasovilya and @LukasSarnowskiC9,
I've faced the same issue but it still doesn't work for me.

```
self.addEventListener('notificationclick', function(event) {
        function sendMsg(client, url, notification) {
            client.postMessage(self.JSON.stringify({ url, notification }));
        }

        function openUrl(openingUrl) {
            return self.clients.openWindow(openingUrl);
        }
        event.notification.close();

        const data = event.notification.data;
        const url = data.url;
        const notification = data.notification;

        event.waitUntil(
            self.clients
                .matchAll({ type: 'window', includeUncontrolled: true })
                .then(function(clientList) {
                    const nonNested = clientList.filter(client => client.frameType !== 'nested');

                    // if there are no non-framed clients, just open the new window with the specified url
                    if (nonNested.length === 0) {
                        return openUrl(url);
                    } else {
                        for (let i = 0; i < clientList.length; i++) {
                            const firstClient = nonNested[i];

                            if ('focus' in firstClient) {
                                return firstClient
                                    .focus()
                                    .then(sendMsg.bind(null, firstClient, url, notification))
                                    .catch(openUrl.bind(null, url));
                            }
                        }
                    }
                })
        );
    });
```

Could you please share your piece of code which is working on Canary?

**Comment by ManalLiaquat** [comment]
@LukasSarnowskiC9 Can you please tell me how did you test your TWA in `chrome canary`? Because TWA always opens in default `chrome` browser. How did you specify to open in canary instead of chrome? Or did you mean `PWA`, not `TWA`?
